# Generated by Django 5.0.6 on 2024-06-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varsity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20, null=True)),
                ('major', models.CharField(max_length=20)),
                ('image_front', models.ImageField(null=True, upload_to='varsity/')),
                ('image_back', models.ImageField(null=True, upload_to='varsity/')),
                ('like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, null=True)),
                ('varsity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='main.varsity')),
            ],
        ),
    ]
