<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-20 13:33
=======
# Generated by Django 5.0.6 on 2024-06-20 13:32
>>>>>>> b44485314ff0876bb5c21f7ab570147be99709c6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_varsity_image_back_alter_varsity_image_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varsity',
            name='like_count',
        ),
        migrations.CreateModel(
            name='Varsitylike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0)),
<<<<<<< HEAD
                ('like', models.ManyToManyField(null=True, related_name='likes', to='main.varsity')),
=======
                ('like', models.ManyToManyField(blank=True, related_name='likes', to='main.varsity')),
>>>>>>> b44485314ff0876bb5c21f7ab570147be99709c6
            ],
        ),
    ]
